language: python
python:
  - "3.7"

# install dependencies
install:
  - cd BSPQ20E3
  - python setup.py install

# need mongo first
services:
  - mongodb

# test stuff
script:
  - cd BSPQ20E3
  - python manage.py test

# build master branch
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - asierfdln@opendeusto.es
      - imanolgonzalezestepa@opendeusto.es
      - badiolajulen@opendeusto.es
      - rulegua@opendeusto.es
      - marta.madariaga99@opendeusto.es
    on_success: always
    on_failure: always