language: python
python:
  - "3.7"

install:
  - pip install -r requiredlibs.txt

services:
  - mongodb

# test stuff
script:
  - cd BSPQ20E3
  - python manage.py test

# will only build master branch
branches:
  only:
    - master